/** Палитры по типу бизнеса */
export const TYPE_PALETTES = {
  barbershop: {
    primary_color: '#C17A4A',
    accent_color: '#F5D0A8',
    secondary_color: '#E8D5C4',
    background_color: '#0f0d0b',
    surface_color: '#1a1612',
    text_color: '#f5f0eb',
    button_text_color: '#1a1208',
  },
  salon: {
    primary_color: '#D4649A',
    accent_color: '#FFD6E8',
    secondary_color: '#F0C4D8',
    background_color: '#100c10',
    surface_color: '#1a1418',
    text_color: '#fdf2f8',
    button_text_color: '#2a0818',
  },
  nails: {
    primary_color: '#E879A9',
    accent_color: '#FBCFE8',
    secondary_color: '#F9A8D4',
    background_color: '#120a10',
    surface_color: '#1c1218',
    text_color: '#fdf2f8',
    button_text_color: '#2a0818',
  },
  brows: {
    primary_color: '#C4A484',
    accent_color: '#E8D5C4',
    secondary_color: '#D4C4B0',
    background_color: '#100e0c',
    surface_color: '#1a1614',
    text_color: '#f5f0eb',
    button_text_color: '#1a1208',
  },
  tattoo: {
    primary_color: '#7C3AED',
    accent_color: '#C4B5FD',
    secondary_color: '#A78BFA',
    background_color: '#0c0a12',
    surface_color: '#16121f',
    text_color: '#f5f3ff',
    button_text_color: '#12081f',
  },
  massage: {
    primary_color: '#0D9488',
    accent_color: '#99F6E4',
    secondary_color: '#5EEAD4',
    background_color: '#0a1010',
    surface_color: '#121a1a',
    text_color: '#f0fdfa',
    button_text_color: '#042f2e',
  },
  cosmetology: {
    primary_color: '#DB2777',
    accent_color: '#FBCFE8',
    secondary_color: '#F9A8D4',
    background_color: '#120a10',
    surface_color: '#1c1218',
    text_color: '#fdf2f8',
    button_text_color: '#500724',
  },
  makeup: {
    primary_color: '#EC4899',
    accent_color: '#F9A8D4',
    secondary_color: '#F472B6',
    background_color: '#120a10',
    surface_color: '#1c1218',
    text_color: '#fdf2f8',
    button_text_color: '#500724',
  },
  epilation: {
    primary_color: '#F59E0B',
    accent_color: '#FDE68A',
    secondary_color: '#FCD34D',
    background_color: '#120e08',
    surface_color: '#1c1610',
    text_color: '#fffbeb',
    button_text_color: '#451a03',
  },
  tutor: {
    primary_color: '#5B7CFA',
    accent_color: '#B8C9FF',
    secondary_color: '#C5D4FF',
    background_color: '#0a0c12',
    surface_color: '#121820',
    text_color: '#eef2ff',
    button_text_color: '#0a1020',
  },
  other: {
    primary_color: '#2AABEE',
    accent_color: '#F5C542',
    secondary_color: '#E8EAED',
    background_color: '#0b0d10',
    surface_color: '#14181f',
    text_color: '#f3f4f6',
    button_text_color: '#0b0d10',
  },
}

export const ACCENT_SWATCHES = [
  { id: 'warm', primary: '#C17A4A', accent: '#F5D0A8', label: 'Тёплый' },
  { id: 'rose', primary: '#D4649A', accent: '#FFD6E8', label: 'Розовый' },
  { id: 'blue', primary: '#5B7CFA', accent: '#B8C9FF', label: 'Синий' },
  { id: 'mint', primary: '#2DD4BF', accent: '#99F6E4', label: 'Мятный' },
  { id: 'tg', primary: '#2AABEE', accent: '#F5C542', label: 'Telegram' },
]

export function paletteForType(type) {
  return TYPE_PALETTES[type] || TYPE_PALETTES.other
}
